services:
  tunnel-client:
    build: .
    container_name: tunnel-client
    restart: unless-stopped
    ports:
      - "3002:3000"
    volumes:
      - ./credentials.json:/app/credentials.json
      - frpc-config:/etc/frp
    environment:
      - TZ=UTC
      - SERVER_URL=http://tunnel.ersantana.com:8000
      - TUNNEL_TOKEN
      - FRPC_ADMIN_URL=http://frpc:7400
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frpc:
    image: snowdreamtech/frpc:0.52.3
    container_name: frpc
    restart: unless-stopped
    volumes:
      - frpc-config:/etc/frp
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - tunnel-client

volumes:
  frpc-config:
